### PR TITLE
Hotfix: Update README.rst

### PR DESCRIPTION
**Pull request by passive-radio**
## What
Fixed style for restructured text (prev commit was in the style of markdown.)

### CODE REVIEW

**Review by obitsu-jo — APPROVED** [review]
I confirmed the previous format was not viewable and it has been fixed in this commit.

**Review by vantelindome — APPROVED** [review]
LGTM! Thank you for your update!

**Comment by passive-radio** [comment]
@obitsu-jo 
> I confirmed the previous format was not viewable and it has been fixed in this commit.
Please approve commits through Commits > Review > Approve feature.

2024-11-21 02_13_42-Arc

**Comment by vantelindome** [comment]
@passive-radio 
I think people who don't have write access of this repository cannot be counted on approval...

**Pull request merged**
