### PR TITLE
Update documents

### PR DESCRIPTION
**Pull request by flat35hd99**

### CODE REVIEW

**Review by flat35hd99 — COMMENTED** [review]
LGTM

**Comment by flat35hd99** [comment]
@yamato97 I create single commit to resolve conflict. Almost changes on `patch` branch took a priority. One point did not take a priority because the change looks not correct. You can check [that I change](https://github.com/yamatolab/current-calculations-for-proteins/pull/24/commits/ecf1f5faf23da84f9c77dec311b8d72e7f7c0aea)

**Comment by flat35hd99** [comment]
@vantelindome This change is completely same with [this pull request](https://github.com/yamatolab/current-calculations-for-proteins/pull/21). Could you check that these pull request is same ?

**Review by vantelindome — APPROVED** [review]

**Review by yamato97 — COMMENTED** [review]
To make sure several issues/questions, I sent a slack message to @flat35hd99 . I'm a little bit confused about the patch branch of this repository.

**Comment by yamato97** [comment]
Now I think my comments have been addressed successfully.

**Review by yamato97 — APPROVED** [review]

**Pull request merged**
