### PR TITLE
Document Continuous Deployment using GitHub Actions

### PR DESCRIPTION
**Pull request by flat35hd99**
[demo](https://flat35hd99.github.io/current-calculations-for-proteins/) is available.

This branch forked by master branch because There are a lot of diff between master and develop branches. This is bad manner but we cannot wait deploying website on new site.

### CODE REVIEW

**Review by vantelindome — COMMENTED** [review]
no need to change

**Comment by flat35hd99** [comment]
GitHub Actions is defined in `.github/workflows/deploy_doc.yaml`. The previous one ignore all of name `.` start. Thus, I delete them.

**Review by vantelindome — APPROVED** [review]
I see.

**Review by yamato97 — APPROVED** [review]

**Comment by flat35hd99** [comment]
close #7

**Pull request merged**
