### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by passive-radio**
## Why
- Want to motivate developer to develop this library
- Want to motivate potential users to try this library

## What
Added a budge to visualize the number of downloads on README.

### CODE REVIEW

**Comment by passive-radio** [comment]
This budge will be displayed on README
20241109_01_13_26-curp download stats - Vivaldi

**Review by yamato97 — APPROVED** [review]
Big surprise at such as many as 20k downloads! Nice idea to add that badge.

**Review by vantelindome — APPROVED** [review]
LGTM! I also think that's could be a motivator!

**Comment by passive-radio** [comment]
Thank you!
I'll merge this PR.

**Pull request merged**
